package com.dglt.statement.vo;

public class ReportName {
	// 报表ID 3001 本地调度——调度基本台帐报表 对应localDispatchLedger.jspp页面
	public final static String sql_3001 = "select distinct t2.form_no,t1.form_title,t2.bss_customer_name,t1.send_user_id,t2.biz_type,t2.customer_type from t_form_main t1,T_FORM_LOCAL_DISPATCH  t2 where t2.parent_form_id=t1.pk_id";

	public final static String[] arr_3001 = { "form_no", "form_title",
			"bss_customer_name", "send_user_id", "biz_type", "customer_type" };

	// 售前工单查询 3002
	public final static String sql_3002 = "select * from"
												+"(select distinct fm.req_type,fm.prcs_inst_id,fm.pk_id pk_id,ww.workitemid,ww.activityinstid,fm.form_seq form_seq,to_char(fm.send_time, 'yyyy-mm-dd hh24:mi:ss') send_time,fm.form_title form_title,fp.assessment_score assessment_score,p.user_name user_name,ww.partiname partiname,p.dept_name dept_name,case when fp.assessment_score is NULL then null else to_char(fp.last_updated_date, 'yyyy-mm-dd hh24:mi:ss')end assessment_time,ev.enum_value_meaning enum_value_meaning,row_number()OVER(PARTITION BY fm.form_seq order by ww.workitemid desc) row_id"
												+"      from T_FORM_MAIN        fm,T_FORM_PRESALES    fp,info_person        p,T_APP_ENUM_VALUE   ev,wfwiparticipant ww"
												+"      where ww.workitemname like '%技术方案制定'and ww.participantname = ww.partiname and ww.partiintype = 'EXE' and ww.processinstid = fm.prcs_inst_id and fp.parent_form_id = fm.pk_id and fp.form_no = fm.form_seq and fm.send_user_id = p.user_id and fp.assessment_result = ev.enum_value(+) and ev.enum_item_code(+) = 'assessmentResult' and 1 = 1"
												+"union"
												+" select distinct fm.req_type,fm.prcs_inst_id,fm.pk_id pk_id,ww.workitemid,ww.activityinstid,fm.form_seq form_seq,to_char(fm.send_time, 'yyyy-mm-dd hh24:mi:ss') send_time,fm.form_title form_title,fp.assessment_score assessment_score,p.user_name user_name,ww.partiname partiname,p.dept_name dept_name,case when fp.assessment_score is NULL then null else to_char(fp.last_updated_date, 'yyyy-mm-dd hh24:mi:ss')end assessment_time,ev.enum_value_meaning enum_value_meaning,row_number()OVER(PARTITION BY fm.form_seq order by ww.workitemid desc) row_id"
												+"      from T_FORM_MAIN        fm,T_FORM_PRESALES    fp,info_person        p,T_APP_ENUM_VALUE   ev,wf_h_wiparticipant ww"
												+"      where ww.workitemname like '%技术方案制定'and ww.participantname = ww.partiname and ww.partiintype = 'EXE' and ww.processinstid = fm.prcs_inst_id and fp.parent_form_id = fm.pk_id and fp.form_no = fm.form_seq and fm.send_user_id = p.user_id and fp.assessment_result = ev.enum_value(+) and ev.enum_item_code(+) = 'assessmentResult' and 1 = 1"
												+""
												+" ) t where t.row_id=1 order by fm.prcs_inst_id desc";

	public final static String[] arr_3002 = { "req_type","prcs_Inst_Id", "form_main_id",
			"workitemid", "activityinstid", "form_seq", "send_time",
			"form_title", "assessment_score", "user_name", "partiname",
			"dept_name", "assessment_time", "enum_value_meaning","rowid" };
	
public final static String sql_90013 ="select  distinct tfm.req_type,tfm.prcs_inst_id,tfm.pk_id,wi.workitemid,wi.activityinstid,tfm.form_seq,tfld.form_no form_no,tfm.form_title form_title,tfld.bss_customer_name bss_customer_name,ip.user_name applicant,taev1.enum_value_meaning bizType,taev2.enum_value_meaning customerType,tfld.circuit_no ciruit_no,tfld.Wire_Speed wire_speed,tfld.WIRE_SPEED_UNIT wire_speed_unit,tfld.PORTA_TYPE porta_type,tfld.portb_type portb_type,tfld.OTHER_RESOURCE other_resource,tfld.TRANS_RESOURCE_ROUTE trans_resource_route,tfld.trans_resource_circuit trans_resource_circuit,tfld.Trans_Resource trans_resource,tfld.switch_resource switch_resource,tfld.DATA_RESOURCE data_resource,tfld.Disform_Desc disform_desc,tfld.BSS_PRODUCT_NO bss_product_no,tfld.CUSTOMER_ADDRESS customer_address,tfld.CUSTOMER_CONTACT customer_contact from t_form_main tfm,T_FORM_LOCAL_DISPATCH  tfld,info_person ip,T_APP_ENUM_VALUE taev1,T_APP_ENUM_VALUE taev2,wfworkitem wi where tfld.parent_form_id=tfm.pk_id and tfm.send_user_id=ip.user_id and (taev1.enum_item_code(+)='businessType' and taev1.enum_value_num(+)=tfld.biz_type) and(taev2.enum_item_code(+)='customerType' and taev2.enum_value_num(+)=tfld.customer_type) and wi.processinstid=tfm.prcs_inst_id and tfm.form_status!=1 and wi.activitydefid= case when tfld.attribute1 is null then 'DraftActivity' else 'planMakeActivity' end";
	
	
	
public final static String sql_90014 ="select distinct tfm.req_type,tfm.prcs_inst_id,tfm.pk_id,wi.workitemid,wi.activityinstid,tfm.form_seq,tfbd.form_no form_no,tfm.form_title form_title,tc.user_name customer_name,ip.user_name applicant, taev2.enum_value_meaning biztype,taev2.enum_value_meaning customertype,tfbd.circuit_code ciruit_no,tfbd.attribute2 wire_speed,tfbd.attribute2 other_resource,tfbd.attribute2 trans_resource,tfbd.attribute2 switch_resource,tfbd.attribute2 data_resource,tfbd.form_context form_context,tfbd.product_num bss_product_no,tfbd.RELATED_CUSTOMER customer_address,tfbd.tel_num customer_contactfrom from T_FORM_MAIN tfm,T_FORM_BSS_DISA tfbd,t_Form_Customer tfc,t_customer tc,T_APP_ENUM_VALUE taev2,info_person ip,wfworkitem wi where tfm.form_status!=1 and (tfbd.product_type(+)=taev2.enum_value and taev2.enum_item_code(+)='prdCategoryBss') and tfm.send_user_id=ip.user_id and tfc.main_pk_id=tfbd.parent_form_id and tfbd.parent_form_id=tfm.pk_id and tfc.cust_pk_id=tc.pk_id and wi.processinstid=tfm.prcs_inst_id and wi.activitydefid= 'DraftActivity'";


public final static String sql_90016 =
									"select w1.req_type,w1.prcs_inst_id,w1.pk_id,w1.workitemid,w1.activityinstid,w1.form_seq,w1.form_no,w1.form_title,w1.form_type,w1.applicant,w1.send_time,w1.cust_level,taev.enum_value_meaning forms_tatus,w1.user_name participantname,w1.bizType,w1.customer_address,w1.disformType from ("
									+"select w.req_type,w.prcs_inst_id,w.pk_id,w.workitemid,w.activityinstid,w.form_seq,w.form_no,w.form_title,w.form_type,w.applicant,w.send_time,w.cust_level,w.formstatus,ip.user_name,w.bizType,w.customer_address,w.disformType,w.row_id from(select  distinct tfm.req_type,tfm.prcs_inst_id,tfm.pk_id,ww.workitemid,ww.activityinstid,tfm.form_seq,tfld.form_no,tfm.form_title form_title,taev1.enum_value_meaning form_type,ip.user_name applicant,tfm.send_time,tc.cust_level,case when (ww.activitydefid = 'DraftActivity' and ww.currentstate = 10 and ww.partiintype = 'EXE') then '11' else  tfm.form_status end formstatus,case when ww.participantname is null then (select itu.user_id from info_team_user itu where itu.team_id=ww.participantid ) else ww.participantid end participantid,taev2.enum_value_meaning bizType,tfld.CUSTOMER_ADDRESS customer_address,taev3.enum_value_meaning disformType,1 row_id  from t_form_main tfm,T_FORM_LOCAL_DISPATCH  tfld,info_person ip,T_APP_ENUM_VALUE taev1,T_APP_ENUM_VALUE taev2,T_APP_ENUM_VALUE taev3,t_customer tc,t_Form_Customer tfc,WFWIPARTICIPANT ww where tc.pk_id = tfc.cust_pk_id and tfc.main_pk_id=tfm.pk_id and tfld.parent_form_id=tfm.pk_id and  tfm.send_user_id=ip.user_id and  tfm.req_type=taev1.enum_value and (taev2.enum_item_code(+)='businessType'and tfld.biz_type =taev2.enum_value(+) )and(tfld.disform_type(+)=taev3.enum_value and taev3.enum_item_code(+)='disformType') and ww.processinstid = tfm.prcs_inst_id and ((ww.currentstate='10' and ww.partiintype='EXE') or (ww.currentstate='4' and ww.partiintype='GET') )  and 1=1)w,info_person ip where w.participantid=ip.user_id"
									+" union "
									+ "select * FROM (select w.*,row_number() OVER (PARTITION BY w.prcs_inst_id order by workitemid desc) row_id   from"                 
																		+"(select  distinct tfm.req_type,tfm.prcs_inst_id,tfm.pk_id,ww.workitemid,ww.activityinstid,tfm.form_seq,tfld.form_no,tfm.form_title form_title,taev1.enum_value_meaning,  ip.user_name applicant,tfm.send_time,tc.cust_level,case when (ww.activitydefid = 'DraftActivity' and ww.currentstate = 10 and ww.partiintype = 'EXE') then '11' else  tfm.form_status end form_status,null participantname,taev2.enum_value_meaning bizType,tfld.CUSTOMER_ADDRESS customer_address,taev3.enum_value_meaning disformType from t_form_main tfm,T_FORM_LOCAL_DISPATCH  tfld,info_person ip,T_APP_ENUM_VALUE taev1,T_APP_ENUM_VALUE taev2,T_APP_ENUM_VALUE taev3,t_customer tc,t_Form_Customer tfc,wf_h_wiparticipant ww  where tfm.form_status!='1' and tc.pk_id = tfc.cust_pk_id and tfc.main_pk_id=tfm.pk_id and tfld.parent_form_id=tfm.pk_id and  tfm.send_user_id=ip.user_id and  tfm.req_type=taev1.enum_value and (taev2.enum_item_code(+)='businessType'and tfld.biz_type =taev2.enum_value(+) )and(tfld.disform_type(+)=taev3.enum_value and taev3.enum_item_code(+)='disformType') and ww.processinstid = tfm.prcs_inst_id and ww.partiintype='EXE' and (ww.currentstate='12'or ww.currentstate='13') and 1=1) w )where row_id=1"
									+")w1,T_APP_ENUM_VALUE taev where (taev.enum_item_code(+)='reportFormStatus' and w1.formstatus=taev.enum_value(+)) order by w1.form_seq desc";		

public final static String sql_90017 =" select t.apply_form_req_type,t.apply_form_prcs_inst_id,t.apply_form_pk_id,t.apply_form_activityinstid,t.apply_form_workitemid,t.cst_form_req_type,t.cst_form_prcs_inst_id,t.cst_form_pk_id,t.cst_form_activityinstid,t.cst_form_workitemid,t.apply_form_title,t.dept_name,t.APPLY_FORM_IS_CROSS_DOMAIN,t.cust_level,fn_getenumvaluename('departmentArea', t.lanch_area) as apply_form_lanch_area_name,fn_getenumvaluename('blongTeam', t.prj_blong_team) as apply_form_blongTeam,t.bss_pdc_no,t.estimated_income,t.prj_act_invt_amount,t.additional_income,t.contract_term,t.start_charge_time,t.user_name,t.apply_form_seq,fn_getenumvaluename('formStatus', t.apply_form_status) as apply_form_status,to_char(t.apply_form_sendtime, 'yyyy-mm-dd hh24:mi:ss') apply_form_sendtime,to_char(t.apply_form_endtime, 'yyyy-mm-dd hh24:mi:ss') apply_form_endtime,round(nvl(t.apply_form_endtime, sysdate) - t.apply_form_sendtime, 2) apply_form_dealtime,t.cst_form_seq,fn_getenumvaluename('formStatus', t.cst_form_status) as cst_form_status,to_char(t.cst_form_sendtime, 'yyyy-mm-dd hh24:mi:ss') cst_form_sendtime,t.prj_impl_period,t.limit_time,to_char(t.cst_form_endtime, 'yyyy-mm-dd hh24:mi:ss') cst_form_endtime,round(nvl(t.cst_form_endtime, sysdate) - t.cst_form_sendtime, 2) cst_form_dealtime,case when not (t.cst_form_endtime is null) then round((t.cst_form_endtime - t.limit_time), 2) else null end cst_form_overtime,case when t.cst_form_endtime is null then '否 ' when round(t.cst_form_endtime - t.limit_time) >= 0 then '是 ' else '否 ' end cst_form_isovertime"
		+"   from (select wi.workitemid cst_form_workitemid,wi.activityinstid cst_form_activityinstid,wi.activitydefid activitydefid2,case when wi.activitydefid = 'ConfirmFinishActivity' then wi.endtime else null end cst_form_endtime,case when B.activitydefid1 = 'DraftActivity' then '11' else B.form_status1 end apply_form_status,case when wi.activitydefid = 'DraftActivity' then '11' else B.form_status2 end cst_form_status,B.*,row_number() OVER(PARTITION BY B.cst_form_prcs_inst_id order by wi.workitemid desc) rowidB"
		+"           from (select wi.workitemid apply_form_workitemid,wi.activityinstid apply_form_activityinstid,wi.activitydefid activitydefid1,wi.endtime apply_form_endtime,A.*,row_number() OVER(PARTITION BY A.apply_form_prcs_inst_id order by wi.workitemid desc) rowidA"
		+"                   from (select distinct tfm1.prcs_inst_id apply_form_prcs_inst_id,tfm1.pk_id apply_form_pk_id,tfm2.pk_id cst_form_pk_id,tfm1.req_type apply_form_req_type,tfm2.req_type cst_form_req_type,tfm2.prcs_inst_id cst_form_prcs_inst_id,tfm1.form_title apply_form_title,ip.dept_name,case when tfp.IS_CROSS_DOMAIN = 'Y' then '是' when tfp.IS_CROSS_DOMAIN = 'N' then '否' else tfp.IS_CROSS_DOMAIN end APPLY_FORM_IS_CROSS_DOMAIN, tc.cust_level,tfp.lanch_area,tfp.prj_blong_team,tfpr.bss_pdc_no,tfp.estimated_income,tfp.attribute3 prj_act_invt_amount,tfp.additional_income,tfp.attribute2 contract_term,tfpr.start_charge_time,ip.user_name,tfm1.form_seq apply_form_seq,tfm1.form_status form_status1,tfm1.send_time apply_form_sendtime,tfm2.form_seq cst_form_seq,tfm2.send_time cst_form_sendtime,tfp.prj_impl_period,(tfm2.send_time + to_number(tfp.prj_impl_period)) limit_time,tfm2.form_status form_status2"
		+"                           from t_form_main     tfm1,t_form_main     tfm2,T_FORM_PRJAPPLY tfp,info_person     ip,t_customer      tc,t_Form_Customer tfc,T_FORM_PRJCST   tfpr  "
		+"                           where tfm1.pk_id = tfp.parent_form_id and tfpr.parent_form_id = tfm2.pk_id and tfm1.send_user_id = ip.user_id and tc.pk_id = tfc.cust_pk_id and tfc.main_pk_id = tfm1.pk_id and tfpr.prjapply_pkid = tfp.pk_id and 1 = 1 ) A,"
		+"                        wfworkitem wi "
		+"           where A.apply_form_prcs_inst_id = wi.processinstid) B,wfworkitem wi"
		+"   where B.cst_form_prcs_inst_id = wi.processinstid and B.rowidA = 1 and wi.activitydefid in('DraftActivity','SysRecordActivity','OrgConstrActivity','PrjSealBbActivity','WzBuyActivity','BssAduitActivity','ConfirmFinishActivity')) t"
		+"  where rowidB = 1 and 2 = 2 and 3 = 3";

  public final static String sql_90015 =
										" select * from ( "
												+" select w1.*,taev5.enum_value_meaning formstatus from ( select w.*,row_number() OVER (PARTITION BY w.processinstid order by w.endtime desc) row_id from ( select distinct tfm.req_type,tfm.prcs_inst_id,tfm.pk_id,wp.workitemid,wp.activityinstid,tfm.form_seq,tfld.form_no,  wp.processinstid, case when((select count(*) from WFWIParticipant wp1 where  wp1.currentstate=10 and wp1.activityinstname  in ('本地调度单提交','调度方案制定','负责人审核','业务管理部门审批','业务管理部门经理审批','集客部领导审批','调度审核','调度审核与反馈') and wp1.processinstid = wp.processinstid)>0) then null else  to_char(wp.endtime,'yyyy-mm-dd hh24:mi:ss') end endtime,tfm.form_title, taev2.enum_value_meaning customertype,taev3.enum_value_meaning bizType,tfld.BSS_PRODUCT_NO product_no, ip.user_name,ip.dept_name, case when (select count(*) from WFWIParticipant wp2 where  wp2.currentstate=10 and wp2.activitydefid = 'DraftActivity' and wp2.partiintype = 'EXE' and  wp2.processinstid=wp.processinstid )>0 then '11' else  tfm.form_status  end form_status,tfm.send_time,(select count(*) from t_form_step tfp where  tfp.opt_type='rejectToStart' and tfp.prcs_inst_id= tfm.prcs_inst_id )  RetsCount     ,case when (   (select count(*) from t_form_step tfp1 where  tfp1.opt_type='rejectToStart' and tfp1.prcs_inst_id = tfm.prcs_inst_id )>0) then tfp.opt_comment  else null    end   reason from t_form_main tfm,info_person ip,WFWIPARTICIPANT wp,t_form_local_dispatch tfld,T_APP_ENUM_VALUE taev2,T_APP_ENUM_VALUE taev3,t_form_step tfp  where  tfm.form_status!=1 and  tfm.prcs_inst_id=tfp.prcs_inst_id  and tfld.parent_form_id=tfm.pk_id and (taev2.enum_item_code(+)='customerType' and taev2.enum_value_num(+)=tfld.customer_type) and (taev3.enum_item_code(+)='businessType' and taev3.enum_value_num(+)=tfld.biz_type) and tfp.opt_type='rejectToStart' and  wp.processinstid = tfm.prcs_inst_id and tfm.send_user_id=ip.user_id   and (wp.currentstate = 10 or wp.currentstate = 12 or wp.currentstate = 13) and wp.partiintype='EXE' and wp.activityinstname  in ('本地调度单提交','调度方案制定','负责人审核','业务管理部门审批','业务管理部门经理审批','集客部领导审批','调度审核','调度审核与反馈','资源使用情况回复')  and 1=1 ) w)w1,T_APP_ENUM_VALUE taev5 where  (taev5.enum_item_code(+)='reportFormStatus' and taev5.enum_value(+)=w1.form_status)and w1.row_id=1 "
												+" union"
												+" select w1.*,taev5.enum_value_meaning formstatus from ( select w.*,row_number() OVER (PARTITION BY w.processinstid order by w.endtime desc) row_id from ( select distinct  tfm.req_type,tfm.prcs_inst_id,tfm.pk_id,wp.workitemid,wp.activityinstid,tfm.form_seq,tfld.form_no,  wp.processinstid, case when((wp.activityinstname  in ('本地调度单提交','调度方案制定','负责人审核','业务管理部门审批','业务管理部门经理审批','集客部领导审批','调度审核','调度审核与反馈') )) then null else  to_char(wp.endtime,'yyyy-mm-dd hh24:mi:ss') end  endtime,tfm.form_title, taev2.enum_value_meaning customertype,taev3.enum_value_meaning bizType,tfld.BSS_PRODUCT_NO product_no, ip.user_name,ip.dept_name, tfm.form_status  form_status,tfm.send_time,0  RetsCount, null  reason from t_form_main tfm,info_person ip,WFWIPARTICIPANT wp,t_form_local_dispatch tfld,T_APP_ENUM_VALUE taev2,T_APP_ENUM_VALUE taev3  where  tfm.form_status!=1 and   tfld.parent_form_id=tfm.pk_id and (taev2.enum_item_code(+)='customerType' and taev2.enum_value_num(+)=tfld.customer_type) and(taev3.enum_item_code(+)='businessType' and  taev3.enum_value_num(+)=tfld.biz_type) and  wp.processinstid = tfm.prcs_inst_id and tfm.send_user_id=ip.user_id   and ( (wp.currentstate = 12 and wp.partiintype='EXE' ))and '13' not in (select wp1.currentstate from WFWIPARTICIPANT wp1 where  wp1.processinstid=wp.processinstid ) and wp.activityinstname  in ('本地调度单提交','调度方案制定','负责人审核','业务管理部门审批','业务管理部门经理审批','集客部领导审批','调度审核','调度审核与反馈','资源使用情况回复') and 1=1  ) w)w1,T_APP_ENUM_VALUE taev5 where  (taev5.enum_item_code(+)='reportFormStatus' and taev5.enum_value(+)=w1.form_status)and w1.row_id=1 "
												+" union"
												+" select w1.*,taev5.enum_value_meaning formstatus from ( select w.*,row_number() OVER (PARTITION BY w.processinstid order by w.endtime desc) row_id from ( select distinct  tfm.req_type,tfm.prcs_inst_id,tfm.pk_id,wp.workitemid,wp.activityinstid,tfm.form_seq,tfld.form_no,  wp.processinstid, case when((select count(*) from wf_h_wiparticipant wp1 where  wp1.currentstate=10 and wp1.activityinstname  in ('本地调度单提交','调度方案制定','负责人审核','业务管理部门审批','业务管理部门经理审批','集客部领导审批','调度审核','调度审核与反馈') and wp1.processinstid = wp.processinstid)>0) then null else  to_char(wp.endtime,'yyyy-mm-dd hh24:mi:ss') end endtime,tfm.form_title, taev2.enum_value_meaning customertype,taev3.enum_value_meaning bizType,tfld.BSS_PRODUCT_NO product_no, ip.user_name,ip.dept_name, tfm.form_status  form_status,tfm.send_time,(select count(*) from t_form_step tfp where  tfp.opt_type='rejectToStart' and tfp.prcs_inst_id= tfm.prcs_inst_id )  RetsCount, (select tfp1.opt_comment from t_form_step tfp1 where  tfp1.opt_type='stopProcess' and tfp1.prcs_inst_id = tfm.prcs_inst_id ) reason from t_form_main tfm,info_person ip,wf_h_wiparticipant wp,t_form_local_dispatch tfld,T_APP_ENUM_VALUE taev2,T_APP_ENUM_VALUE taev3,t_form_step tfp  where  tfm.form_status!=1 and tfm.prcs_inst_id=tfp.prcs_inst_id  and tfld.parent_form_id=tfm.pk_id and (taev2.enum_item_code(+)='customerType' and taev2.enum_value_num(+)=tfld.customer_type) and (taev3.enum_item_code(+)='businessType' and taev3.enum_value_num(+)=tfld.biz_type) and tfp.opt_type='stopProcess' and  wp.processinstid = tfm.prcs_inst_id and tfm.send_user_id=ip.user_id  and wp.partiintype='EXE' and wp.activityinstname  in ('本地调度单提交','调度方案制定','负责人审核','业务管理部门审批','业务管理部门经理审批','集客部领导审批','调度审核','调度审核与反馈','资源使用情况回复') and 1=1 and tfm.form_status=4 and (wp.currentstate = 12 or wp.currentstate = 13)) w)w1,T_APP_ENUM_VALUE taev5 where  (taev5.enum_item_code(+)='reportFormStatus' and taev5.enum_value(+)=w1.form_status)and w1.row_id=1 "
												+" union"
												+" select w1.*,taev5.enum_value_meaning formstatus from ( select w.*,row_number() OVER (PARTITION BY w.processinstid order by w.endtime desc) row_id from ( select distinct  tfm.req_type,tfm.prcs_inst_id,tfm.pk_id,wp.workitemid,wp.activityinstid,tfm.form_seq,tfld.form_no,  wp.processinstid, case when((select count(*) from wf_h_wiparticipant wp1 where  wp1.currentstate=10 and wp1.activityinstname  in ('本地调度单提交','调度方案制定','负责人审核','业务管理部门审批','业务管理部门经理审批','集客部领导审批','调度审核','调度审核与反馈') and wp1.processinstid = wp.processinstid)>0) then null else  to_char(wp.endtime,'yyyy-mm-dd hh24:mi:ss') end endtime,tfm.form_title, taev2.enum_value_meaning customertype,taev3.enum_value_meaning bizType,tfld.BSS_PRODUCT_NO product_no, ip.user_name,ip.dept_name, case when (select count(*) from wf_h_wiparticipant wp2 where  wp2.currentstate=10 and wp2.activitydefid = 'DraftActivity' and wp2.partiintype = 'EXE' and  wp2.processinstid=wp.processinstid )>0 then '11' else  tfm.form_status    end form_status,tfm.send_time,(select count(*) from t_form_step tfp where  tfp.opt_type='rejectToStart' and tfp.prcs_inst_id= tfm.prcs_inst_id )  RetsCount     ,case when (  (select count(*) from t_form_step tfp1 where  tfp1.opt_type='rejectToStart' and tfp1.prcs_inst_id = tfm.prcs_inst_id )>0) then tfp.opt_comment else null   end   reason from t_form_main tfm,info_person ip,wf_h_wiparticipant wp,t_form_local_dispatch tfld,T_APP_ENUM_VALUE taev2,T_APP_ENUM_VALUE taev3,t_form_step tfp  where  tfm.form_status!=1 and  tfm.prcs_inst_id=tfp.prcs_inst_id  and tfld.parent_form_id=tfm.pk_id and (taev2.enum_item_code(+)='customerType' and taev2.enum_value_num(+)=tfld.customer_type) and (taev3.enum_item_code(+)='businessType' and taev3.enum_value_num(+)=tfld.biz_type) and  wp.processinstid = tfm.prcs_inst_id and tfm.send_user_id=ip.user_id  and wp.partiintype='EXE' and wp.activityinstname  in ('本地调度单提交','调度方案制定','负责人审核','业务管理部门审批','业务管理部门经理审批','集客部领导审批','调度审核','调度审核与反馈','资源使用情况回复') and 1=1 and tfm.form_status!=4 and  (wp.currentstate = 12 or wp.currentstate = 13)) w)w1,T_APP_ENUM_VALUE taev5 where  (taev5.enum_item_code(+)='reportFormStatus' and taev5.enum_value(+)=w1.form_status)and w1.row_id=1  "
												+" union"
												+" select w1.*,taev5.enum_value_meaning formstatus from ( select w.*,row_number() OVER (PARTITION BY w.processinstid order by w.endtime desc) row_id from ( select distinct tfm.req_type,tfm.prcs_inst_id,tfm.pk_id,wp.workitemid,wp.activityinstid,tfm.form_seq,tfld.form_no,  wp.processinstid, case when((select count(*) from WFWIParticipant wp1 where  wp1.currentstate=10 and wp1.activityinstname  in   ('发单人申请','分管领导/总结审批','集客部审核','国际业务中心审核','一站式系统受阻','BSS系统操作拆机','处理环节','调度数据拆除资源回收')  and wp1.processinstid = wp.processinstid)>0) then null  else  to_char(wp.endtime,'yyyy-mm-dd hh24:mi:ss') end endtime,tfm.form_title, taev3.enum_value_meaning customertype,taev3.enum_value_meaning biztype,tfld.product_num product_no, ip.user_name,ip.dept_name, case when (select count(*) from WFWIParticipant wp2 where  wp2.currentstate=10 and wp2.activitydefid = 'DraftActivity' and wp2.partiintype = 'EXE' and  wp2.processinstid=wp.processinstid )>0 then '11' else  tfm.form_status    end form_status,tfm.send_time,(select count(*) from t_form_step tfp where  tfp.opt_type='rejectToStart' and tfp.prcs_inst_id= tfm.prcs_inst_id )  RetsCount     ,case when (   (select count(*) from t_form_step tfp1 where  tfp1.opt_type='rejectToStart' and tfp1.prcs_inst_id = tfm.prcs_inst_id )>0) then tfp.opt_comment  else null    end    reason from t_form_main tfm,info_person ip,WFWIPARTICIPANT wp,t_form_bss_disa tfld,T_APP_ENUM_VALUE taev2, T_APP_ENUM_VALUE taev3,t_form_step tfp  where  tfm.form_status!=1 and  tfm.prcs_inst_id=tfp.prcs_inst_id and tfld.parent_form_id=tfm.pk_id and  (tfld.product_type=taev2.enum_value(+) and taev2.enum_item_code(+)='prdCategoryBss') and (tfld.product_type(+)=taev3.enum_value and taev3.enum_item_code(+)='prdCategoryBss')  and tfp.opt_type='rejectToStart'  and  wp.processinstid = tfm.prcs_inst_id and tfm.send_user_id=ip.user_id   and (wp.currentstate = 10 or wp.currentstate = 12 or wp.currentstate = 13) and wp.partiintype='EXE' and wp.activityinstname  in  ('发单人申请','分管领导/总监审批','集客部审核','国际业务中心审核','一站式系统受阻','BSS系统操作拆机','处理环节','调度数据拆除资源回收','外线拆除资产回收') and 1=1 ) w)w1,T_APP_ENUM_VALUE taev5 where  (taev5.enum_item_code(+)='reportFormStatus' and taev5.enum_value(+)=w1.form_status)and w1.row_id=1 "
												+" union"
												+" select w1.*,taev5.enum_value_meaning formstatus from ( select w.*,row_number() OVER (PARTITION BY w.processinstid order by w.endtime desc) row_id from ( select distinct  tfm.req_type,tfm.prcs_inst_id,tfm.pk_id,wp.workitemid,wp.activityinstid,tfm.form_seq,tfld.form_no,  wp.processinstid, case when((wp.activityinstname  in   ('发单人申请','分管领导/总结审批','集客部审核','国际业务中心审核','一站式系统受阻','BSS系统操作拆机','处理环节','调度数据拆除资源回收') )) then null  else  to_char(wp.endtime,'yyyy-mm-dd hh24:mi:ss') end endtime,tfm.form_title, taev3.enum_value_meaning customertype,taev3.enum_value_meaning biztype,tfld.product_num product_no,  ip.user_name,ip.dept_name,  tfm.form_status  form_status,tfm.send_time,0  RetsCount, null  reason from t_form_main tfm,info_person ip,WFWIPARTICIPANT wp,t_form_bss_disa tfld,T_APP_ENUM_VALUE taev2,T_APP_ENUM_VALUE taev3 where  tfm.form_status!=1 and   tfld.parent_form_id=tfm.pk_id and  (tfld.product_type=taev2.enum_value(+) and taev2.enum_item_code(+)='prdCategoryBss') and (tfld.product_type(+)=taev3.enum_value and taev3.enum_item_code(+)='prdCategoryBss') and  wp.processinstid = tfm.prcs_inst_id and tfm.send_user_id=ip.user_id   and ( (wp.currentstate = 12 and wp.partiintype='EXE' ))and '13' not in (select wp1.currentstate from WFWIPARTICIPANT wp1 where  wp1.processinstid=wp.processinstid ) and wp.activityinstname  in  ('发单人申请','分管领导/总结审批','集客部审核','国际业务中心审核','一站式系统受阻','BSS系统操作拆机','处理环节','调度数据拆除资源回收','外线拆除资产回收')  and 1=1 ) w)w1,T_APP_ENUM_VALUE taev5 where  (taev5.enum_item_code(+)='reportFormStatus' and taev5.enum_value(+)=w1.form_status)and w1.row_id=1 "
												+" union"
												+"  select w1.*,taev5.enum_value_meaning formstatus from ( select w.*,row_number() OVER (PARTITION BY w.processinstid order by w.endtime desc) row_id from ( select distinct  tfm.req_type,tfm.prcs_inst_id,tfm.pk_id,wp.workitemid,wp.activityinstid,tfm.form_seq,tfld.form_no,  wp.processinstid, case when((select count(*) from wf_h_wiparticipant wp1 where  wp1.currentstate=10 and wp1.activityinstname  in  ('发单人申请','分管领导/总结审批','集客部审核','国际业务中心审核','一站式系统受阻','BSS系统操作拆机','处理环节','调度数据拆除资源回收') and wp1.processinstid = wp.processinstid)>0) then null else  to_char(wp.endtime,'yyyy-mm-dd hh24:mi:ss') end endtime,tfm.form_title, taev3.enum_value_meaning customertype,taev3.enum_value_meaning biztype,tfld.product_num product_no, ip.user_name,ip.dept_name, tfm.form_status  form_status,tfm.send_time,(select count(*) from t_form_step tfp where  tfp.opt_type='rejectToStart' and tfp.prcs_inst_id= tfm.prcs_inst_id )  RetsCount,(select tfp1.opt_comment from t_form_step tfp1 where  tfp1.opt_type='stopProcess' and tfp1.prcs_inst_id = tfm.prcs_inst_id ) reason from t_form_main tfm,info_person ip,wf_h_wiparticipant wp,t_form_bss_disa tfld,T_APP_ENUM_VALUE taev2, T_APP_ENUM_VALUE taev3,t_form_step tfp  where  tfm.form_status!=1 and tfm.prcs_inst_id=tfp.prcs_inst_id  and tfld.parent_form_id=tfm.pk_id and  (tfld.product_type=taev2.enum_value(+) and taev2.enum_item_code(+)='prdCategoryBss') and (tfld.product_type(+)=taev3.enum_value and taev3.enum_item_code(+)='prdCategoryBss') and tfp.opt_type='stopProcess' and  wp.processinstid = tfm.prcs_inst_id and tfm.send_user_id=ip.user_id   and tfm.form_status=4 and wp.partiintype='EXE' and wp.activityinstname  in  ('发单人申请','分管领导/总结审批','集客部审核','国际业务中心审核','一站式系统受阻','BSS系统操作拆机','处理环节','调度数据拆除资源回收','外线拆除资产回收')  and 1=1 ) w)w1,T_APP_ENUM_VALUE taev5 where  (taev5.enum_item_code(+)='reportFormStatus' and taev5.enum_value(+)=w1.form_status)and w1.row_id=1 "
												+" union"
												+"  select w1.*,taev5.enum_value_meaning formstatus from ( select w.*,row_number() OVER (PARTITION BY w.processinstid order by w.endtime desc) row_id from ( select distinct  tfm.req_type,tfm.prcs_inst_id,tfm.pk_id,wp.workitemid,wp.activityinstid,tfm.form_seq,tfld.form_no,  wp.processinstid, case when((select count(*) from wf_h_wiparticipant wp1 where  wp1.currentstate=10 and wp1.activityinstname  in  ('发单人申请','分管领导/总结审批','集客部审核','国际业务中心审核','一站式系统受阻','BSS系统操作拆机','处理环节','调度数据拆除资源回收') and wp1.processinstid = wp.processinstid)>0) then  null else  to_char(wp.endtime,'yyyy-mm-dd hh24:mi:ss') end endtime,tfm.form_title, taev3.enum_value_meaning customertype,taev3.enum_value_meaning biztype,tfld.product_num product_no, ip.user_name,ip.dept_name, case when (select count(*) from wf_h_wiparticipant wp2 where  wp2.currentstate=10 and wp2.activitydefid = 'DraftActivity' and wp2.partiintype = 'EXE' and  wp2.processinstid=wp.processinstid )>0 then '11' else  tfm.form_status    end form_status,tfm.send_time,(select count(*) from t_form_step tfp where  tfp.opt_type='rejectToStart' and tfp.prcs_inst_id= tfm.prcs_inst_id )  RetsCount     ,case when (   (select count(*) from t_form_step tfp1 where  tfp1.opt_type='rejectToStart' and tfp1.prcs_inst_id = tfm.prcs_inst_id )>0) then tfp.opt_comment  else null   end   reason from t_form_main tfm,info_person ip,wf_h_wiparticipant wp,t_form_bss_disa tfld, T_APP_ENUM_VALUE taev2,T_APP_ENUM_VALUE taev3,t_form_step tfp  where  tfm.form_status!=1 and  tfm.prcs_inst_id=tfp.prcs_inst_id  and tfld.parent_form_id=tfm.pk_id and  (tfld.product_type=taev2.enum_value(+) and taev2.enum_item_code(+)='prdCategoryBss') and (tfld.product_type(+)=taev3.enum_value and taev3.enum_item_code(+)='prdCategoryBss')  and  wp.processinstid = tfm.prcs_inst_id and tfm.send_user_id=ip.user_id   and tfm.form_status!=4 and wp.partiintype='EXE' and wp.activityinstname  in  ('发单人申请','分管领导/总结审批','集客部审核','国际业务中心审核','一站式系统受阻','BSS系统操作拆机','处理环节','调度数据拆除资源回收','外线拆除资产回收')  and 1=1 ) w)w1,T_APP_ENUM_VALUE taev5 where  (taev5.enum_item_code(+)='reportFormStatus' and taev5.enum_value(+)=w1.form_status)and w1.row_id=1 "
												+" ) order by form_seq desc";


	public final static String[] arr_90013 = {"req_type","prcs_Inst_Id","form_main_id","workitemid","activityinstid","form_seq","form_no","form_title","bss_customer_name", 
		"applicant", "biztype", "customertype", "ciruit_no", "wire_speed",  
		"wire_speed_unit","porta_type", "portb_type", "other_resource", 
		"trans_resource_route", "trans_resource_circuit", "trans_resource", 
		"switch_resource", "data_resource", "disform_desc", 
		"bss_product_no", "customer_address", 
		"customer_contact"};
	
	
	
	public final static String[] arr_90014 = {"req_type","prcs_Inst_Id","form_main_id","workitemid","activityinstid","form_seq","form_no","form_title","customer_name", 
		"applicant", "biztype", "customertype", "ciruit_no", "wire_speed",  
		 "other_resource", 
		"trans_resource",
		"switch_resource", "data_resource", "form_context", 
		"bss_product_no", "customer_address", 
		"customer_contact"};
	
	public final static String[] arr_90015 ={"req_type","prcs_Inst_Id","form_main_id","workitemid","activityinstid","form_seq","form_no","processinstid","endtime","form_title","customertype",
		"biztype","product_no","user_name","dept_name","form_status","send_time","retcount", "reason","row_id", "form_status"};
	
	
	public final static String[] arr_90016 ={"req_type","prcs_Inst_Id","form_main_id","workitemid","activityinstid","form_seq","form_no","form_title","form_type",
		"applicant", "send_time", "cust_level","form_status", "participantname", "bizType",
		"customer_address","disformType"};
	public final static String[] arr_90017 = {"apply_form_req_type","apply_form_prcs_inst_id","apply_form_pk_id","apply_form_activityinstid","apply_form_workitemid","cst_form_req_type","cst_form_prcs_inst_id","cst_form_pk_id","cst_form_activityinstid","cst_form_workitemid","apply_form_title","dept_name","apply_form_is_cross_domain","cust_level","apply_form_lanch_area_name","apply_form_blongteam","bss_pdc_no","estimated_income","prj_act_invt_amount","additional_income","contract_term","start_charge_time","user_name","apply_form_seq","apply_form_status","apply_form_sendtime","apply_form_endtime","apply_form_dealtime","cst_form_seq","cst_form_status","cst_form_sendtime","prj_impl_period","limit_time","cst_form_endtime","cst_form_dealtime","cst_form_overtime","cst_form_isovertime"};


}
